let wordDictionary = {
  pomme: "🍎",
  banane: "🍌",
  bang: "💥",
  baseball: "⚾",
  basketball: "🏀",
  bière: "🍺",
  vélo: "🚴",
  bombe: "💣",
  garçon: "👦",
  insecte: "🐛",
  burger: "🍔",
  brûler: "🔥",
  gâteau: "🎂",
  bonbon: "🍬",
  chat: "🐱",
  célébration: "🎉",
  cheeseburger: "🍔",
  cookie: "🍪",
  cool: "😎",
  pleurer: "😢",
  chien: "🐶",
  chienne: "🐕",
  terre: "🌎",
  exploser: "💥",
  péter: "💨",
  rapide: "💨",
  femme: "👩",
  feu: "🔥",
  poisson: "🐟",
  flamme: "🔥",
  fleur: "🌹",
  nourriture: "🍕",
  football: "🏈",
  fille: "👧",
  golf: "⛳",
  hamburger: "🍔",
  heureux: "😀",
  cheval: "🐴",
  baiser: "😘",
  rire: "😂",
  allumé: "🔥",
  verrou: "🔒",
  lol: "😂",
  mâle: "👨",
  homme: "👨",
  singe: "🐵",
  lune: "🌙",
  note: "📝",
  peinture: "🎨",
  panda: "🐼",
  fête: "🎉",
  cochon: "🐷",
  pizza: "🍕",
  planète: "🌎",
  rose: "🌹",
  rofl: "😂",
  triste: "😢",
  dormir: "😴",
  sourire: "😀",
  soccer: "⚽",
  étoile: "⭐",
  soleil: "☀️",
  "lunettes de soleil": "😎",
  surpris: "😮",
  arbre: "🌲",
  trophée: "🏆",
  gagner: "🏆",
  vent: "💨",
  vin: "🍷",
  "clin d'œil": "😉",
  monde: "🌎",
  wow: "😮",
  canard: "🦆",
  papillon: "🦋",
  lapins: "🐇",
  poules: "🐔",
  écureuil: "🐿️",
  renard: "🦊",
  chouette: "🦉",
  héron: "🦢",
  grenouilles: "🐸",
  pattes: "🐾",
  pizza: "🍕",
  hamburger: "🍔",
  frites: "🍟",
  "hot dog": "🌭",
  sandwich: "🥪",
  taco: "🌮",
  burrito: "🌯",
  "pop corn": "🍿",
  sushi: "🍣",
  riz: "🍚",
  nouilles: "🍜",
  spaghetti: "🍝",
  pain: "🍞",
  croissant: "🥐",
  baguette: "🥖",
  fromage: "🧀",
  bacon: "🥓",
  oeuf: "🍳",
  salade: "🥗",
  tomate: "🍅",
  carotte: "🥕",
  brocoli: "🥦",
  poivron: "🫑",
  concombre: "🥒",
  aubergine: "🍆",
  haricot: "🌱",
  maïs: "🌽",
  "pomme de terre": "🥔",
  champignon: "🍄",
  oignon: "🧅",
  ail: "🧄",
  poivre: "🫑",
  sel: "🧂",
  sucre: "🍬",
  gateau: "🍰",
  glace: "🍨",
  chocolat: "🍫",
  bonbon: "🍭",
  biscuit: "🍪",
  "pain d'épices": "🧁",
  beignet: "🍩",
  fruit: "🍎",
  poire: "🍐",
  banane: "🍌",
  orange: "🍊",
  citron: "🍋",
  fraise: "🍓",
  cerise: "🍒",
  pastèque: "🍉",
  raisin: "🍇",
  ananas: "🍍",
  mangue: "🥭",
  pomme: "🍏",
  abricot: "🍑",
  noix: "🥜",
  noisette: "🌰",
  amande: "🌰",
  pistache: "🥜",
  kiwi: "🥝",
  avocat: "🥑",
  grenade: "🫒",
  figue: "🫐",
  châtaigne: "🌰",
  pêche: "🍑",
  légume: "🥬",
  "glace à la vanille": "🍦",
  "glace au chocolat": "🍨",
  "glace à la fraise": "🍓",
  sorbet: "🍧",
  yaourt: "🥛",
  lait: "🥛",
  café: "☕",
  thé: "🍵",
  jus: "🧃",
  soda: "🥤",
  bière: "🍺",
  vin: "🍷",
  cocktail: "🍹",
  champagne: "🍾",
  bouteille: "🍾",
  verre: "🥃",
  cuillère: "🥄",
  fourchette: "🍴",
  couteau: "🔪",
  assiette: "🍽️",
  bol: "🥣",
  pot: "🍯",
  poêle: "🍳",
  hachoir: "🔪",
  thermomètre: "🌡️",
  balance: "⚖️",
  coeur: "❤️",
  rire: "😂",
  "pleurer de rire": "😅",
  "clin d oeil": "😉",
  baiser: "😘",
  surpris: "😮",
  triste: "😢",
  "en colère": "😡",
  endormi: "😴",
  étoile: "⭐",
  soleil: "☀️",
  lune: "🌙",
  éclair: "⚡",
  nuage: "☁️",
  "arc en ciel": "🌈",
  fleur: "🌸",
  café: "☕",
  gâteau: "🎂",
  cadeau: "🎁",
  musique: "🎵",
  sport: "⚽",
  livre: "📚",
  ordinateur: "💻",
  téléphone: "📱",
  voiture: "🚗",
  avion: "✈️",
  bateau: "⛵",
  train: "🚂",
  vélo: "🚲",
  maison: "🏠",
  ville: "🏙️",
  plage: "🏖️",
  montagne: "⛰️",
  camping: "⛺",
  "pique-nique": "🧺",
  feu: "🔥",
  eau: "💧",
  médaille: "🏅",
  trophée: "🏆",
  clé: "🔑",
  cadenas: "🔒",
  loupe: "🔍",
  horloge: "🕒",
  ampoule: "💡",
  drapeau: "🚩",
  planète: "🌍",
  fusée: "🚀",
  microscope: "🔬",
  télescope: "🔭",
  rouge: "🟥",
  orange: "🟧",
  jaune: "🟨",
  vert: "🟩",
  bleu: "🟦",
  violet: "🟪",
  rose: "🟫",
  noir: "⬛",
  blanc: "⬜",
  gris: "🟨",
  marron: "🟫",
  turquoise: "🟦",
  famille: "👨‍👩‍👧‍👦",
  maman: "👩",
  papa: "👨",
  bébé: "👶",
  enfant: "🧒",
  fille: "👧",
  garçon: "👦",
  "grand mère": "👵",
  "grand père": "👴",
  "femme enceinte": "🤰",
  biberon: "🍼",
  chaise: "🪑",
  lit: "🛏️",
  doudou: "🧸",
  poussin: "🐥",
  dort: "😴",
  mouton: "🐑",
  immeuble: "🏢",
  école: "🏫",
  bureau: "💼",
  hôpital: "🏥",
  banque: "🏦",
  poste: "🏣",
  église: "⛪",
  mosquée: "🕌",
  temple: "🕍",
  château: "🏰",
  musée: "🏛️",
  cinéma: "🎦",
  théâtre: "🎭",
  stade: "🏟️",
  restaurant: "🍽️",
  café: "☕",
  bibliothèque: "📚",
  supermarché: "🛒",
  aéroport: "🛫",
  gare: "🚉",
  "station service": "⛽",
  casino: "🎰",
  voiture: "🚗",
  taxi: "🚕",
  bus: "🚌",
  métro: "🚇",
  train: "🚆",
  tramway: "🚋",
  vélo: "🚲",
  moto: "🏍️",
  scooter: "🛵",
  camion: "🚚",
  avion: "✈️",
  hélicoptère: "🚁",
  fusée: "🚀",
  bateau: "⛵",
  navire: "🚢",
  canoë: "🛶",
  "sous-marin": "🚤",
  skateboard: "🛹",
  roller: "🛼",
  trottinette: "🛴",
  marche: "🚶",
  course: "🏃",
  ski: "⛷️",
  snowboard: "🏂",
  luge: "🛷",
  surf: "🏄‍♂️",
  natation: "🏊‍♂️",
  plongée: "🤿",
  escalade: "🧗",
  parachute: "🪂",
  "moto neige": "🏂",
  montgolfière: "🎈",
  "voiture de course": "🏎️",
  tracteur: "🚜",
  "voiture de police": "🚓",
  ambulance: "🚑",
  "camion de pompiers": "🚒",
  "bus scolaire": "🚍",
  dent: "🦷",
  "t-shirt": "👕",
  chemise: "👔",
  robe: "👗",
  pantalon: "👖",
  veste: "🧥",
  "sweat-shirt": "👚",
  "haut de forme": "🎩",
  "maillot de bain": "🩱",
  bikini: "👙",
  chaussures: "👟",
  talons: "👠",
  bottes: "👢",
  sandales: "👡",
  chaussettes: "🧦",
  nœud: "🎀",
  casquette: "🧢",
  gants: "🧤",
  écharpe: "🧣",
  parapluie: "☂️",
  montre: "⌚",
  bague: "💍",
  "sac à main": "👜",
  "sac à dos": "🎒",
  valise: "🧳",
  princesse: "👸",
  roi: "🤴",
  couronne: "👑",
  château: "🏰",
  danger: "⚠️",
  crotte: "💩",
  écureuil: "🐿️",
  oiseaux: "🐦",
  seau: "🪣",
};

let wordMap = {};

for (let word in wordDictionary) {
  wordMap[wordDictionary[word]] = word;
}

let originalText = {};

chrome.runtime.onMessage.addListener(function (request, sender, sendResponse) {
  let elements = document.querySelectorAll("p, div, span, b, m");

  for (let index = 0; index < elements.length; index++) {
    if (request.method === "translateToEmojis") {
      originalText[index] = elements[index].innerHTML;

      elements[index].innerHTML = elements[index].innerHTML.replace(
        /(\b[\w\u00C0-\u017F]+\b)/gm,
        function (word) {
          let lowerCaseWord = word.toLowerCase();
          let emoji =
            wordDictionary[lowerCaseWord] ||
            wordDictionary[lowerCaseWord.slice(0, -1)];
          return emoji ? `<span class="emoji">${emoji}</span>` : word;
        }
      );
    } else if (request.method === "translateToWords") {
      elements[index].innerHTML =
        originalText[index] || elements[index].innerHTML;
    }
  }
});
